RemoteTechnologiesGroup/RemoteTech

GameData/RemoteTech/RemoteTech_AIES_Antennas.cfg
GameData/RemoteTech/RemoteTech_AIES_Probes.cfg
GameData/RemoteTech/RemoteTech_Antennas.cfg
GameData/RemoteTech/RemoteTech_B9_Probes.cfg
GameData/RemoteTech/RemoteTech_FASA_Antennas.cfg
GameData/RemoteTech/RemoteTech_FASA_Probes.cfg
GameData/RemoteTech/RemoteTech_LLL_Antennas.cfg
GameData/RemoteTech/RemoteTech_LLL_Probes.cfg
GameData/RemoteTech/RemoteTech_MechJeb.cfg
GameData/RemoteTech/RemoteTech_NearFuture_Probes.cfg
GameData/RemoteTech/RemoteTech_NovaPunch_Probes.cfg
GameData/RemoteTech/RemoteTech_Squad_Antennas.cfg
GameData/RemoteTech/RemoteTech_Squad_Probes.cfg

Added configs for AIES, Lack Luster Labs, Near-Future Spacecraft, and NovaPunch.
I'm not very confident about the balance for the antennas, especially for LLL -- those dishes make absolutely no attempt to be stockalike. Maybe we need some good rules of thumb (see #122, #126) for antenna properties?

More part configs

---

src/RemoteTech/UI/TimeWarpDecorator.cs

Changed back the 3 point floating delay to 5 and fixed the position of the delay text
Preview

Small tweaks

---

src/RemoteTech/NetworkRenderer.cs
src/RemoteTech/RTSettings.cs

- added a new setting `HideGroundStationsBehindBody` to hide ground
station if they are behind its body
closes #241

 Possibility to hide ground stations

---

src/RemoteTech/UI/AbstractWindow.cs
src/RemoteTech/UI/FilterOverlay.cs
src/RemoteTech/UI/FocusOverlay.cs

 Hide Windows/Overlays when the GUI is hidden

---

src/RemoteTech/NetworkManager.cs
src/RemoteTech/NetworkRenderer.cs
src/RemoteTech/RangeModel/RangeModelExtensions.cs

Modified the two places that currently call GetPositionFromGuid() to handle the null value instead of handling an exception. This is more in line with RemoteTechologiiesGroup "codiing style" to not throw execptions where possible.

Changed GetPositionFromGuid() to return a nullabe Vector3d

---

src/RemoteTech/UI/AttitudeFragment.cs

Changed buttons from state to action on the flightcomputer. This closes #212

Changed buttons on flightcomputer

---

src/RemoteTech/NetworkRenderer.cs
src/RemoteTech/RangeModel/RangeModelExtensions.cs

- removed log spamming by null targets
- UpdateNetworkCones now checks if the target is a target or not
Fix #282

Small fixes

---

GameData/RemoteTech/RemoteTech.version
src/RemoteTech/Properties/AssemblyInfo.cs
src/RemoteTech/RTCore.cs
src/RemoteTech/RTUtil.cs

Also added a new getter for the AssemblyVersion in RTUtil and log this number on the `loaded successfully` notifycation.

Updated the Assembly Version

---

src/RemoteTech/UI/AntennaWindow.cs
src/RemoteTech/UI/FilterOverlay.cs

Reposition of the targetinfo trigger to get a better result

Targetwindow lag on mouseover listentrys

---

src/RemoteTech/Properties/AssemblyInfo.cs

Update KSPAssembly to 1.6

---

src/RemoteTech/FlightComputer/Commands/AttitudeCommand.cs
src/RemoteTech/FlightComputer/FlightComputer.cs
src/RemoteTech/RTUtil.cs
src/RemoteTech/RemoteTech.csproj
src/RemoteTech/SimpleTypes/ComputerModeMapper.cs
src/RemoteTech/UI/AttitudeFragment.cs
src/RemoteTech/UI/FlightComputerWindow.cs

The new action buttons do not show the actual flight mode. You only can see the actual mode with a open queue-window. This is why i made a *Fake-Toggle-Action-Button*. It's still an action button but with a state to change the background color.
Resolves #212

Fake toggle buttons

---

src/RemoteTech/Properties/AssemblyInfo.cs

Duplicate of PR #318 - but on the 1.7.0 branch.

Don't change AssemblyVersion except on major/minor updates.

---

src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs

- added a save method to be sure the nodeIndex is on the meneuvernode list
- some other checks added
- changed the mode after a meneuver command from off to KillRot

ManeuverCommand load save fix

---

src/RemoteTech/NetworkPathfinder.cs

This pr fixes #312. I use the code snippet of Taste83(#139) and added a task that i'll look closer to this if i'm more releated to the NetworkPathfinder.
Edit: this also fixes #101

Fix for zero cost links

---

src/RemoteTech/FlightComputer/EventCommand.cs

- added a save method to save the flightid of the part from the queued BaseEvent
- added extra checks to be sure the BaseEvent is loaded
Fixes #320 
This pr was validated by Synighte via pm

Fix EventCommand load/save

---

CHANGES.md
GameData/RemoteTech/RemoteTech.version
src/RemoteTech/Properties/AssemblyInfo.cs

- Updated CHANGES.md
- Updated AVC Version file
- Updated Assembly Version

Release v1.6.2

---

src/RemoteTech/RTUtil.cs

I changed the read out of the AssemblyVersion to the AssemblyFileVersion to get also the third part of the current version.

AssemblyVersion read out changed

---

src/RemoteTech/SatelliteManager.cs

We can't re-register a station with only a ModuleSPUPassive. Thats why i'll try to look for a ModuleSPU before i return a ModuleSPUPassiv.
Fixes #338

Changed the GetSignalProcessor-method

---

CHANGES.md
GameData/RemoteTech/RemoteTech.version
src/RemoteTech/Properties/AssemblyInfo.cs

- Added download URL on the AVC-Version-File to kerbalstuff
- copyright updated on the assembly file

Release v1.6.3

---

src/RemoteTech/RTUtil.cs
src/RemoteTech/UI/AbstractWindow.cs
src/RemoteTech/UI/AttitudeFragment.cs

I added two new methods to the `RTUtil` class.
- RepeatButton(...)
- MouseWheelTriggerField(...)
Both methods can be used to trigger an event more than once. I changed the flightcomputer Pitch/Heading & Roll buttons und input fields to these new methods. I also had to add a new ControlLock for the `CAMERACONTROLS` to the `AbstractWindow.setWindowCtrlLock()` method.
Closes #283

Added +/- trigger buttons

---

src/RemoteTech/API/API.cs
src/RemoteTech/FlightComputer/RoverComputer.cs
src/RemoteTech/Modules/ModuleSPU.cs
src/RemoteTech/RTUtil.cs
src/RemoteTech/SatelliteManager.cs
src/RemoteTech/UI/AntennaWindow.cs
src/RemoteTech/UI/FilterOverlay.cs
src/RemoteTech/UI/TargetInfoFragment.cs
src/RemoteTech/UI/TargetInfoWindow.cs
src/RemoteTech/VesselExtension.cs
src/RemoteTech/VesselSatellite.cs

You will have to forgive me for mixing a bunch of small code cleanup in with the API fix.

Take two api

---

guide/settings.md

These are updates to the RemoteTech documentation.

Added docs for `Additive` model, and HideGroundStationsBehindBody.

---

src/RemoteTech/UI/FlightComputerWindow.cs

We disabled the rovercomputer for a later release

Disable Rovercomputer

---

GameData/RemoteTech/Parts/GigaDish1/part.cfg
GameData/RemoteTech/Parts/GigaDish2/part.cfg
GameData/RemoteTech/Parts/LongAntenna2/part.cfg
GameData/RemoteTech/Parts/LongDish1/part.cfg
GameData/RemoteTech/Parts/LongDish2/part.cfg
GameData/RemoteTech/Parts/ShortDish1/part.cfg
GameData/RemoteTech/Parts/ShortDish2/part.cfg

Fixed the bottom attachment points

---

GameData/RemoteTech/RemoteTech_Squad_Probes.cfg

Thanks to klefenz from the forum
Closes #394

Added config for the roverBody

---

src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs

Fixed loading a maneuver command

---

GameData/RemoteTech/Parts/ShortAntenna1/part.cfg

Deleted the stack attach rule because the db-10 has no nodes.
Closes #368

DB-10 attachRules change

---

saves/RemoteTech KSP1_0 Testbed/Ships/SPH/Auto-Saved Ship.craft
saves/RemoteTech KSP1_0 Testbed/Ships/VAB/Auto-Saved Ship.craft
saves/RemoteTech KSP1_0 Testbed/persistent.sfs

- Rover and Narrow Scanner added

Testbed KSP v1.0 Update

---

saves/RemoteTech KSP1_0 Testbed/persistent.sfs

- added Science Station
- added Science Probe

KSP v1.0 Testbed update

---

GameData/RemoteTech/RemoteTech_FASA_Probes.cfg

Added SignalProcessor to Pioneer probe

---

src/RemoteTech/FlightComputer/FlightComputer.cs
src/RemoteTech/NetworkManager.cs
src/RemoteTech/RTSettings.cs
src/RemoteTech/UI/DebugWindow.cs

-  Keep throttle on connection loose 
-  Debug extensions
closes #245
fixed https://github.com/KSP-RO/RP-0/issues/192

Rss ignition fail

---

guide/index.md
tutorials/firstsat.md
tutorials/index.md
tutorials/long_range.md

Primarily fix headings - the `#` needs to have a space between it and the title/heading or it doesn't get rendered as a heading at all.

Fix some markdown syntax

---

GameData/RemoteTech/Default_Settings.cfg
src/RemoteTech/Modules/ModuleSPU.cs
src/RemoteTech/RTSettings.cs
src/RemoteTech/RTSpaceCentre.cs
src/RemoteTech/UI/OptionWindow.cs

- Merged RemoteTechXF and added a `Cheat` Tab to the Option window
- Presets added to the Option window
- Merge mechanism for presets into the game settings file
- Presets can now be reloaded

Option extensions

---

src/RemoteTech/Modules/ModuleRTAntenna.cs

- You can now add the value `IsNonRetractable = boolean` to the antenna section on the part.cfg
closes #463

Antennas can now be non retractable

---

GameData/RemoteTech/Default_Settings.cfg
src/RemoteTech/AddOns/KerbalAlarmClockAPI.cs
src/RemoteTech/FlightComputer/Commands/AbstractCommand.cs
src/RemoteTech/FlightComputer/Commands/AttitudeCommand.cs
src/RemoteTech/FlightComputer/Commands/BurnCommand.cs
src/RemoteTech/FlightComputer/Commands/CancelCommand.cs
src/RemoteTech/FlightComputer/Commands/ICommand.cs
src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs
src/RemoteTech/FlightComputer/FlightComputer.cs
src/RemoteTech/RTCore.cs
src/RemoteTech/RTSettings.cs
src/RemoteTech/RemoteTech.csproj
src/RemoteTech/SimpleTypes/AddOn.cs
src/RemoteTech/UI/OptionWindow.cs

- ManeuverCommands and BurnCommands will now insert an alarm into KerbalAlarmClock.
- ManeuverCommands will now automatically insert a HoldManeuver Command
- Added a new option to aktivate/deaktivate the auto insert to KerbalAlarmClock
closes #304

Burn/Maneuver with KaC Support

---

src/RemoteTech/API/API.cs
src/RemoteTech/AddOns/KerbalAlarmClockAPI.cs
src/RemoteTech/FlightComputer/FlightComputer.cs
src/RemoteTech/Modules/ModuleRTAntenna.cs
src/RemoteTech/Modules/ModuleRTAntennaPassive.cs
src/RemoteTech/Modules/ModuleRTDataTransmitter.cs
src/RemoteTech/Modules/ModuleSPU.cs
src/RemoteTech/Modules/ModuleSPUPassive.cs
src/RemoteTech/RTCore.cs
src/RemoteTech/RTSettings.cs
src/RemoteTech/SimpleTypes/AddOn.cs
src/RemoteTech/UI/OptionWindow.cs

-  Changed preset load priority for default_settings
-  Added a label when no presets was found
-  Fixes for disabled RemoteTech

Small updates/fixes

---

src/RemoteTech/UI/TimeWarpDecorator.cs

Nullref Fix for Scene Transition

---

src/RemoteTech/RTCore.cs
src/RemoteTech/UI/FocusFragment.cs
src/RemoteTech/UI/FocusOverlay.cs

Replicates the behavior of Tracking Station button focus.

---

src/RemoteTech/UI/FocusOverlay.cs

Fixed blank Tracking Station Tracked Objects list

---

src/RemoteTech/Modules/ModuleRTAntenna.cs

Delay antenna destruction due to air pressure by few ticks 

---

src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs

Fixed maneuver node icon not being removed in map view

---

src/RemoteTech/Modules/ModuleRTAntennaPassive.cs
src/RemoteTech/RTPartInfoReloader.cs
src/RemoteTech/RTUtil.cs

Fixing AntennaPassive techrequired

---

GameData/RemoteTech/RemoteTech_NearFuture_Probes.cfg

add near future probe

---

src/RemoteTech/Properties/AssemblyInfo.cs

Update assembly version to 1.7

---

GameData/RemoteTech/RemoteTech_Procedural_Probes.cfg

Add config file for procedural probe cores

---

src/RemoteTech/UI/DebugWindow.cs

Fixed https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/688 issue of the GUIClips spam

Fixed the issue of the GUIClips spam

---

GameData/RemoteTech/RemoteTech_StationPartsExpansion_Probes.cfg

Config for station cores from Stockalike Station Parts Expansion.
http://forum.kerbalspaceprogram.com/index.php?/topic/82833-112-stockalike-station-parts-expansion-01062016-112-update/

Stockalike Station Parts Expansion support

---

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs

If the delta is ~~less~~ more than a constant (0.1f), we don't do anything, the floating point rouding error we are trying to fix here should be really less than 0.1.

Minor fix to patch for issue #667.

---

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs

- Instead of using reflection just add a little bit of additional size to the transmitted frame: KSP will clamp the size to the total packet size anyway.

Rework fix for #667:

---

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs

changed the timing to be based on fixed updates and timewarp instead of just the
coroutine wait time

Better timing for transmitter

---

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs

This checks for the triggered flag before creating the commStream. If the commStream is left null then the process skips the part about pushing data to the R&D center. Instead, after transmission is completed the triggered data transmission event is fired.
An additional bool is added for aborted transmissions, so that the triggered data event can send the correct arguments.

Update to use triggered flag on science data

---

GameData/RemoteTech/RemoteTech_VensStockRevamp.cfg

These Modules seem to be required for the dishes to work.

Fix Ven's Stock Revamp Antennas

---

GameData/RemoteTech/RemoteTech_RestockPlus.cfg
GameData/RemoteTech/RemoteTech_RestockPlus_Antennas.cfg
GameData/RemoteTech/RemoteTech_Restock_Antennas.cfg

This adds support for RestockPlus antennae!

RestockPlus Antenna Support

---

src/RemoteTech/Modules/MissionControlAntenna.cs

Hi! Thank you for a quick reaction to my first PR :)
One more question about mission control dish antennas. Should the dish range be affected by `MissionControlRangeMultiplier` (see the diff)?

Apply MissionControlRangeMultiplier to dish mission control antennas
