RemoteTechnologiesGroup/RemoteTech

src/RemoteTech/FlightComputer/FlightCore.cs
To get the right amount of thrust for all activated and not flamed out engines we had to check against the needed propellants for the engines.
Closes 243
=> Fixed the thrust for flameout engines

src/RemoteTech/RTSettings.cs
Based on Starstriders code. It's now possible to override the RTSettings with `RemoteTechSettings{}` except the MapFilter and ActiveVesselGuid values.
Closes #96
=> Changed settings with GameDatabase

src/RemoteTech/RTSettings.cs, src/RemoteTech/UI/AbstractWindow.cs, src/RemoteTech/UI/AntennaWindow.cs, src/RemoteTech/UI/FlightComputerWindow.cs
Every window position can be saved by setting the `mSavePosition` to true. Actually i've set this to the FlightComputer and AntennaWindow. I also changed the `onPositionChanged` trigger to get a better result.
The positions will only be saved for this ksp instance.
Fixes #21
=> Saves the position of the window

src/RemoteTech/UI/AbstractWindow.cs, src/RemoteTech/UI/AttitudeFragment.cs, src/RemoteTech/UI/QueueFragment.cs
- renamed all remotetech inputs with a small prefix 'rt_'
- added two new methods to the AbstractWindow to handle a stacklock for focused remotetech inputs
Fixes #197
=> Keep keystrokes on inputs

src/RemoteTech/RemoteTech.csproj
It doesnt appear we use these anymore. they were there from the before time. Now i think all they are doing is keeping new people from building the project. Any objection to removing them?
=> removed dependency on task extensions

src/RemoteTech/FlightComputer/Commands/AbstractCommand.cs, src/RemoteTech/FlightComputer/FlightComputer.cs
The `Timestamp` will now be changed by saving the command instead of loading
Resolves #299
=> Fix for the correct ExtraDelay after switching

src/RemoteTech/UI/FocusOverlay.cs
The `mShowOverlay` flag isn't initialized. This is the cause why the satellite fragment is not displayed properly
=> Disappeared sat fragment

src/RemoteTech/FlightComputer/FlightComputer.cs
After rerange the list, some of the items where the condition are also true, will not returned because thay are behind the first fail of the condition (`` c.TimeStamp <= RTUtil.GameTime ``)
Edit: Fixes #305
=> Changed TakeWhile to Where

src/RemoteTech/FlightComputer/Commands/TargetCommand.cs
We got some really weird issues when we save a "none" target, or by loading a target thats already the target of the satellite. This can run into a complete failure of the ksp ui.
This pr can fix #311 , fix #313 and even fix #312
=> Target command fix

src/RemoteTech/Properties/AssemblyInfo.cs
I didn't really understand the distinction between AssemblyVersion, AssemblyFileVersion and AssemblyInformationalVersion until I read this aritcle:
http://www.danielfortunov.com/software/%24daniel_fortunovs_adventures_in_software_development/2009/03/03/assembly_versioning_in_net
In short - please don't update the the AssemblyVersion for major/minor releases, it'll make my life easier in Contract Configurator. :+1:
=> Remove patch version from AssemblyVersion to prevent issues in dependent DLLs

src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs
This fixes #255.
The following tasks were accomplished:
- The remaining deltaV of the maneuver node is now correctly read from the API instead of calculated (the wrong way anyways)
- The current acceleration of the vessel now correctly read from the API instead of calculated (the wrong way anyways)
- I introduced a throttling mechanism at the end of the maneuver burn that aims to hit a target deltaV of 0.0m/s as close as possible. For this kind of new feature I would highly appreciate any comments and especially test results as I tried to cover all cases but one never knows.
=> 255 inaccurate burns

src/RemoteTech/FlightComputer/EventCommand.cs
To load an EventCommand for activating antennas i'll save the name of this event. (for example EventOpen) and search the EventList for the GUIname or the name.
Resolves #329
=> Fix for loading RT EventCommands

src/RemoteTech/SatelliteManager.cs
The problem is that the `v.loaded` on the `GetSignalProcessor` method is still true after the vesselOnRails event. Thats why i also check the `part.count` like we do this on the `SatelliteManager.OnVesselOnRails` method, to search our values on the `ProtoPartModuleSnapshot`.
Fixes #92
=> Fixed KeyNotFoundException

src/RemoteTech/Modules/ProtoSignalProcessor.cs
The `v.GetVesselCrew().count` returns 0 on a `ProtoSignalProcessor`. Thats why i'll look into the `v.protoVessel` to get the crew count.
Fixes #232 
I also added an exception logging for the `getInt` problem.
=> Fix for register a station after unload

src/RemoteTech/API/API.cs, src/RemoteTech/FlightComputer/Commands/AbstractCommand.cs, src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs, src/RemoteTech/RTCore.cs, src/RemoteTech/RemoteTech.csproj
External Mod Code access.
A mod passes a config node to Remotech via code. After the signal delay has passed, Remotech then passes the same config node back to the external mod for the mod to activate. The code below assumes the mod will do all the processing, in this setup Remotetech is only serving as a signal delay on the command.
Using my AGX mod as a demo, here is the code in AGX to pass the configNode to Remotetech:
https://github.com/SirDiazo/AGExt/blob/master/AGExt/Flight.cs#L1571
In the ConfigNode passed, RemoteTech then pulls out the data it needs, Line 101 -105 in Remotetech.API, to make the ICommand to pass to the flight computer.
After the delay has passed, RemoteTech passes the ConfigNode back to the external mod under it's Pop method. Remotetech knows where to send the …
=> Add External Mod access

src/RemoteTech/API/API.cs, src/RemoteTech/RTDebugUnit.cs, src/RemoteTech/RTLog.cs, src/RemoteTech/RemoteTech.csproj, src/RemoteTech/UI/AbstractWindow.cs, src/RemoteTech/UI/DebugWindow.cs
I've added a Debug console for developing purposes only. You can open this window by pressing `F12` but only with a dll that you compiled in debug-mode. You can easily add a new section to this window but actually i've added four sections.
Sometimes i want to do some flightcomputer tests with a high signal delay, or other things without restarting ksp for changing the RTSettings.
To Test and develop new API methods.
You can see the current guid's for each vessel and ground stations. Just copy the guid and use it for the api tester.
On the bottom of this window is a small debug log where you can find only the remotetech notifys oder verbose logs. I also changed the notify methods to give them an `debugLvl: int` to filter your current logs on a new log-window. Current APi-Calls will be …
=> Added a debug console for developing

src/RemoteTech/API/API.cs, src/RemoteTech/RTLog.cs
This adds HasLocalControl to the API, i was building an interface for users in kOS to query stuff about remotetech and i realized i had a few places were we were doing the same calculation that RT is for determining local control. 
If RTs definition for that ever changes, kOS would be out of sync so this new endpoint made sense.
=> Local control API call

src/RemoteTech/AddOns/ControlLockAPI.cs, src/RemoteTech/RTCore.cs, src/RemoteTech/RTLog.cs, src/RemoteTech/RemoteTech.csproj, src/RemoteTech/SimpleTypes/AddOn.cs, src/RemoteTech/UI/AbstractWindow.cs
I've created a new class called `ControlLockAddon` to soft-bind RemoteTech with the new Addon ControlLock created by Diazo. I also created a second class who controls the invokes to the connected
assembly, called `AddOn`.
Also changed:
- a new RTLogLevel = Assembly
- our CtrLock method from `AbstractWindow.setWindowCtrlLock` checks now
if our controlLock is set before setting a new or evene remove
Fixes #197
=> Added "Addon"-loader

src/RemoteTech/API/API.cs, src/RemoteTech/FlightComputer/Commands/AbstractCommand.cs, src/RemoteTech/FlightComputer/Commands/CancelCommand.cs, src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs, src/RemoteTech/FlightComputer/Commands/ICommand.cs, src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs, src/RemoteTech/FlightComputer/Commands/TargetCommand.cs, src/RemoteTech/FlightComputer/EventCommand.cs, src/RemoteTech/UI/DebugWindow.cs
- changed the name from `Api.ReceiveData` to `Api.QueueCommandToFlightComputer`
- The `Api.QueueCommandToFlightComputer` will now return a status if the command was queued successfull
- Changed some values for the parameter of the `Api.QueueCommandToFlightComputer`. Minimum values are now `GUIDString`, `Executor` and `ReflectionType`. Also added a value for the execution
and abort-method.
- fixed a load/save issue for the `ExternalApiCommand`
- also changed the return value of the `ICommand.Load` from void to bool, to determine if the loaded command was successfull or not, before enqueuing to the computer.
Ref task #233
=> ExternalApiCommand refactoring

src/RemoteTech/FlightComputer/Commands/AbstractCommand.cs, src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs, src/RemoteTech/FlightComputer/FlightComputer.cs, src/RemoteTech/UI/DebugWindow.cs
I changed the saving method for each active and queued command. We always passed the complete `flighcomputer`-Node to each command for saving. So this can cause problems by saving a command-data to his own node.
The `ExternalApiCommand` will now save the passed externalData ConfigNode from the API call to the persistent correctly.
Ref task: #233
=> Small fixes

src/RemoteTech/UI/FocusOverlay.cs
Moved the satellite button to the top of the button list.
Preview:
=> Reposition of the satellite button

src/RemoteTech/Modules/ModuleRTAntenna.cs, src/RemoteTech/Modules/ModuleRTAntennaPassive.cs
I think ksp v1.0 can't save a configNode (mTransmitterCofig) properly on the `onLoad()` method. Thats why i use 3 members for the values of the transmitter to build the mTransmitterConfig on the `onStart()` method
Edit: fixes #371
=> Fixed transmit error

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs
If we've a transmission callback parameter we should not stream any data because the `ScienceSubject` from the RnD is null on this kind of transmissions. A ScienceSubject=null causes an exception on the `commStream.StreamData`
Fixes #391
=> Fixed Lab and SurveyScanner transmission error

src/RemoteTech/FlightComputer/UIPartActionMenuPatcher.cs, src/RemoteTech/Modules/ModuleSPU.cs
We also have to change the listParent entry for the current ActionEventItem. I also refactored the UIPartActionMenuPatcher.
Fixes #388
=> Fixed thick text/lag from the context menu

src/RemoteTech/FlightComputer/FlightCore.cs
On KSP 1.0 the ModuleEngineFX is now derived from the ModuleEngine class. Thats why we don't need two loops to calculate the thrust and torque for each class.
Fixes #399
=> Fixed thrust calculation

src/RemoteTech/FlightComputer/FlightComputer.cs
We should sort by the `Delay` value and not the `timestamp`, because the `timestamp = GameTime+SignalDelay` after adding a command and the timestamp value stays always on this value. For a maneuver command we set the `timestamp` value to the burn point. I can't reproduce issue #407 with this change anymore. So i think thats ok.
Fixes #407
=> Correct sorted commands

src/RemoteTech/FlightComputer/FlightComputer.cs
There is no need to throttle back the timewarp on physic warp.
Closes #357
=> No throttling back on phys warp

src/RemoteTech/FlightComputer/EventCommand.cs
If someone throws an exception on a BaseEvent the flight computer tries to invoke over and over. Thats why i catch the exception, make a log entry and ignore the rest.
Fixes #412
=> Catch exceptions for BaseEvents

src/RemoteTech/FlightComputer/Commands/AbstractCommand.cs, src/RemoteTech/FlightComputer/Commands/CancelCommand.cs, src/RemoteTech/FlightComputer/Commands/ICommand.cs
I've create a uniqued number for each `AbstractCommand`. The `CancelCommand` will now cancel the command with its unique number and no longer with the position. I also changed the loading method. We'll no longer search the command to cancel within the loading method, because
this can cause, that we can't find the command to cancel when the CancelCommand is loaded first.
Fixes #408
=> CancelCommand refactoring and changes

src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs, src/RemoteTech/FlightComputer/FlightCore.cs
I'm not good with Quaternions thats why i use the predefined variable `fixedRoll` by Starstrider42. I pass a new parameter `ignoreRoll` to the `HoldOrientation` method to pass it to the `SteeringHelper`. The Roll will no more fixed for: ManeuverNodes, Orbit and Surface maneuvers.
Fixes #340
=> Keep the roll

src/RemoteTech/API/API.cs, src/RemoteTech/AntennaManager.cs, src/RemoteTech/FlightComputer/Commands/TargetCommand.cs, src/RemoteTech/RTUtil.cs, src/RemoteTech/SatelliteManager.cs, src/RemoteTech/UI/SatelliteFragment.cs
I hope this is the last unload error. The problem is that the onRails will be triggered right after 400m. Our condition `v.parts.count==0` is not true and we'll never reregister the satellite. I'll now trigger our
onRails method right after the last part is unloaded.
I've also added a new method `RTUtil.GetVesselById(Guid vesselid)`
Fixes #128 
Fixes #345
=> Fix unload error take 3

GameData/RemoteTech/RemoteTech_CactEye_Probes.cfg
In the CactEye mod a new probe core the Smobodobodyne SLIM has been added. This adds the appropriate RemoteTech functionality.
=> Add RemoteTech_CactEye_Probes.cfg to fix #429

src/RemoteTech/NetworkRenderer.cs
I changed the `CelestialBody` Parameter for the `IsOccluded` call to the satellites body
fixes #440
=> Changed the body determination for a MissionCtrlSat

src/RemoteTech/Modules/ModuleRTAntenna.cs, src/RemoteTech/Modules/ModuleRTAntennaPassive.cs
The method `FindFxModules` only looks into the first module and if this isn't a `iScalarModule` the animation will not be loaded. The parameter `indices` are always empty respectively with one element. (not sure why)
fixes #213
=> Fixed loading animation

src/RemoteTech/Modules/ModuleRTAntenna.cs
Added `onVesselWasModified` Trigger after adding/removing a ModuleRTDataTransmitter from the ship.
fixes #439
=> Added onVesselWasModified Trigger

src/RemoteTech/API/API.cs, src/RemoteTech/IAntenna.cs, src/RemoteTech/Modules/MissionControlAntenna.cs, src/RemoteTech/Modules/ModuleRTAntenna.cs, src/RemoteTech/Modules/ModuleRTAntennaPassive.cs, src/RemoteTech/Modules/ProtoAntenna.cs
Adds `Connected` field to `IAntenna`. This is used to set the antenna status to 'Connected' instead of 'Operational' when antenna is connected. Adds `AntennaHasConnection` method to the API.
Fixes #365.
=> Add an API to get the connection status of an individual antenna

GameData/RemoteTech/RemoteTech_Squad_Antennas.cfg, GameData/RemoteTech/RemoteTech_Squad_Probes.cfg
Add RemoteTech modules for the fairly new Asteroid Day parts. This is the second *official* mod from Squad, RoverDude, and Arsonide. It is available from http://kerbal.curseforge.com/ksp-mods/232196-asteroid-day
Went with standard configuration details for the probe core, and 25Gm range (with above-average power usage, dish angle, and transfer rates) for the antenna. 25Gm *almost* covers Eve's orbit, year-round, directly from Kerbin.
=> Add Asteroid Day Parts

src/RemoteTech/FlightComputer/Commands/TargetCommand.cs, src/RemoteTech/FlightComputer/FlightComputer.cs
Fixes a number of issues with how the flight computer handles vessel targeting:
- All vessels within physics range that were set to `TargetVelocity` or `TargetParallel` would set their attitude relative to the active vessel's target, instead of their own.
- Changing a vessel's target would have no effect while a `TargetCommand` was pending.
- Execution of a `TargetCommand` would overwrite the current target of whatever vessel happened to be active when the command was executed.
=> Clean up vessel target handling

src/RemoteTech/Modules/MissionControlAntenna.cs
- You can now configure a dish antenna to mission control. All mission control dishes are only pointed to the Active Vessel (thx to jdmj)
closes #472
=> Dishes for MissionControl Antennas

src/RemoteTech/Modules/ModuleRTAntenna.cs, src/RemoteTech/RTUtil.cs
For RSS/RO/RP-0 players the eletric consumption of the long antenna is displayed as 0.00/s because we've a formated string with F2 and for this antenna the consumption is 0.0015/s. We'll now tranform all consumptions lower than 1.00/s into minutes. I've also changed the label `Energy req.` into a more stock like label `ElectricCharge`. Also `s` to sec and min for minutes
fixes #487
=> Format consumption fix

src/RemoteTech/Modules/ModuleRTAntenna.cs, src/RemoteTech/Modules/ModuleRTAntennaPassive.cs, src/RemoteTech/Modules/ModuleSPU.cs, src/RemoteTech/RTPartInfoReloader.cs, src/RemoteTech/RTUtil.cs, src/RemoteTech/RemoteTech.csproj
- Added more colors to the editor part infos (more stock like)
- Refactored the unused method RTUtil::IsTechUnlocked(). Parsing the complete
`persistent.sfs` is way to much.
- Fixed an issue where the TechPerk is already available only if i
researched the node but without purchasing the TechPerk-Part it self
- Class ModuleRTAntennaPassive_ReloadPartInfo removed
- New class RTPartInfoReloader created
fixes #489
=> Better editor infos

src/RemoteTech/API/API.cs, src/RemoteTech/RTSettings.cs, src/RemoteTech/UI/AntennaFragment.cs
API to get and set antenna's target.
This required quite a number of methods to be added to the API. The target can be an active vessel, a ground station, a celestial body, any vessel or there can be no target. At first I thought about providing few versions of the same method:
```
SetAntennaTargetToActiveVessel(Part part);
SetAntennaTargetToGroundStation(Part part, String groundStationName);
SetAntennaTargetToCelestialBody(Part part, CelestialBody cb);
...
```
but `GetAntennaTarget(Part part)` would still require the user to figure out what the required Guid (or object) represents. This is why I ended up providing simple `SetAntennaTarget(Part part, Guid id)` and methods to obtain the Guids for various types of objects.
=> SetAntennaTarget API

GameData/RemoteTech/Default_Settings.cfg, src/RemoteTech/Modules/MissionControlAntenna.cs, src/RemoteTech/NetworkManager.cs, src/RemoteTech/NetworkRenderer.cs, src/RemoteTech/RTSettings.cs, src/RemoteTech/RTSpaceCentre.cs, src/RemoteTech/UI/OptionWindow.cs
- The mission control dot on the map view will now be invisible on a defined distance to the camera. See `DistanceToHideGroundStations` on the settings file. This feature can be toggled by the value
`HideGroundStationsOnDistance` in the option window.
- I've added a mouse over info box for each mission control dot on the map view. This feature can be toggled by the value `ShowMouseOverInfoGroundStations` in the option window.
- Ground station antennas can now use the tech level of the tracking station. I've added three new values to the antenna node for a station. Use `UpgradeableOmni`, `UpgradeableDish` and `UpgradeableCosAngle` with a semicolon seperated list of ranges. Example: 4E+06;3.0E+07;7.5E+07
closes #386
- I've added three trigger events for the RTSettings. `OnSettingsChanged` …
=> MissionControl Update pack

src/RemoteTech/UI/TimeWarpDecorator.cs
The label `Local control` and the yellow flight computer button will now change the color when the vessel has no connection.
Connected | Disconnected
------------ | -------------
closes #267
=> Better local control and connected status

src/RemoteTech/API/API.cs, src/RemoteTech/FlightComputer/UIPartActionMenuPatcher.cs
Fixes #437
Provides a workaround so that the original BaseEvent can be called. I hope that in the future #388 will be resolved in some other way and this will not be needed anymore. For now there seems to be no alternative.
=> Provide a way of calling the original BaseEvent

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs
As reported here:
http://forum.kerbalspaceprogram.com/index.php?/topic/75245-105-remotetech-v169-2015-11-10/&page=150#comment-2285093
Also see, e.g. here:
https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/523#issuecomment-178501552
closes #523
closes #520
closes #515
closes #511
=> fix science transmission for KSP 1.0.5

GameData/RemoteTech/Parts/GigaDish1/part.cfg, GameData/RemoteTech/Parts/GigaDish2/part.cfg, GameData/RemoteTech/Parts/LongDish2/part.cfg, GameData/RemoteTech/Parts/ShortDish2/part.cfg
Currently the RT dishes are extremely heavy, not only in comparison to the stock KSP parts, but even in comparison to real life.
With the old masses, there was little incentive to use RT parts, especially unmanned probes with RT dishes for more than kerbin orbital missions. The RT dishes would often be at least as heavy as the whole probe including propulsion.
The proposed values are take from the SETIrebalance mod, where they have been very well recieved for over a year.
Best regards,
Y3mo/Yemo
=> Dish mass adjustments for gameplay and realism reasons

GameData/RemoteTech/Parts/ShortAntenna1/part.cfg
Corrects the attachment distance (gap) of the DP-10.
Also removes physics significance, as is expected of parts with a mass of 5kg (eg z100 battery, thermo, baro). So that the part adds it's mass to the part it is attached to and thus does not skew the center of mass (a common issue for very lightweight DP-10 equipped probes).
Taken from SETI.
Best regards,
Y3mo/Yemo
=> DP-10 attachment and physics significance

GameData/RemoteTech/RemoteTech_VensStockRevamp.cfg
RemoteTech Compatibility Patch For Ven's Stock Revamp
Added everything needed for them to work with RemoteTech but also tweaked several of the stats in an attempt to balance them against existing Stock/RemoteTech dishes.
=> RemoteTech Compatibility Patch For Ven's Stock Revamp

GameData/RemoteTech/Default_Settings.cfg, src/RemoteTech/FlightComputer/Commands/ExternalAPICommand.cs, src/RemoteTech/FlightComputer/Commands/ManeuverCommand.cs, src/RemoteTech/RTSettings.cs
Some minor adjustments to the FC functionality.  Started off by changing FC fallback after execution/abort to Off but then changed replaced that to using a field so it's user configurable.  Also made the lead time on attitude adjustment variable instead of hard coded for 3 minutes. The defaults are mimicking current functionality so nobody loses.  I didn't update the UI to control these settings.
=> Fc execution changes

GameData/RemoteTech/RemoteTech_Antennas.cfg, GameData/RemoteTech/RemoteTech_Squad_Antennas.cfg
- MM patch for new antennas in KSP1.2 adds RT modules and adjusts weight to be more in line with RT antennas 
- includes MM patch to remove ALL occurences of ModuleDataTransmitter as it's now present in command pods too.
- moved DP-10 to start tech to replace the ModuleDataTransmitter removed from command pods.
=> RT config for new stock antennas

src/RemoteTech/Modules/ModuleRTDataTransmitter.cs
Fix for https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/714
=> fix for issue #714, sending whole science amount at the end instead of just a small delta amount

GameData/RemoteTech/RemoteTech_VensStockRevamp.cfg
I added this change to fix the 88-88-V from vens stock revamp not having RemoteTech configs. Let me know if you would prefer me to create an issue or provide more detail in any way. This change only copies the config for the 88-88 to work for the 88-88-V. I can update with logs/modlist/persistent/screenshots if necessary.
O.S: Windows 10 64-bit
KSP: 1.3 64-bit
Problem: New antenna 88-88-V in Vens Stock Revamp does not have RemoteTech configs.
Reproduction steps:
Install RemoteTech and Vens Stock Revamp. Hovering on the 88-88-V in VAB shows no RemoteTech info. Build a ship with the 88-88-V. Launch and fly. No RemoteTech connection.
=> Add RemoteTech config for the Communotron 88-88-V from Vens Stock Revamp

GameData/RemoteTech/Default_Settings.cfg, src/RemoteTech/NetworkManager.cs, src/RemoteTech/RTSettings.cs, src/RemoteTech/UI/DebugWindow.cs, src/RemoteTech/UI/OptionWindow.cs
Without having to go full infinite-propellent which messes with a lot more game mechanics.
~~Ideally I'd also stop having InfinitePropellant also override line-of-sight but I don't want to confuse anyone who is used to using it.~~ YOLO
cc @NathanKell
=> Add cheat option to ignore line-of-sight requirements

src/RemoteTech/API/API.cs, src/RemoteTech/ISatellite.cs, src/RemoteTech/NetworkManager.cs, src/RemoteTech/RTCore.cs, src/RemoteTech/VesselSatellite.cs
Added two methods for a Power Down state.
* `SetPowerDownGuid` method enables/disables a `satellite.IsInPowerDown` mode.
* `GetPowerDownGuid` method returns the state of the `satellite.IsInPowerDown` mode.
I created this functionality for Kerbalism so we can disable satellites when EC is Zero.
I could not use the `IsInRadioBlackout` as it was conflicting with our Blackout system due to it using `IsInRadioBlackout` to detect if the satellite is in Blackout, we do this just in case another mod sets this flag independently of Kerbalism's CME Storms. Setting `IsInRadioBlackout` as a workaround for loss of power would trigger our signals display to show a Blackout for the satellite when there was none.
Adding a check to not show the Blackout condition when EC was zero caused the signals …
=> API methods primarily to support Kerbalism but can be used by others

src/RemoteTech/AddOns/Kerbalism.cs, src/RemoteTech/RTUtil.cs, src/RemoteTech/RemoteTech.csproj
`FormatConsumption` method will display better precision when Kerbalism is detected, needed due to Kerbalism EC costs being much lower than standard RT.
Added a very simple class that detects the presence of Kerbalism into AddOns.
Helps to stop users with Kerbalism being confused when they see something like 0.00/sec rather than 0.240/min
=> Better precision display of EC when Kerbalism is installed

GameData/RemoteTech/RemoteTech_UniversalStorage2_Probes.cfg
Universal Storage has 2 integrated probe cores. Patch file adds the necessary SPU and antenna for them.
As a heads-up, this is based on the current 1.9.1 Beta 5 build of US2. I don't see this changing as I haven't experienced any issues with them, but just wanted to make sure whomever it concerns is aware.
=> Support for Universal Storage 2

GameData/RemoteTech/RemoteTech_Squad_Antennas.cfg
This change duplicates the HighGainAntenna for KSP 1.11 to reflect the v2 part.
=> Duplicate config for HighGainAntenna5 for 1.11
